Repository WordPress/twentytwentythree, pull requests merged in 2022-09, with the labels that each got.

#149 Remove default font size from button elements
  theme.json
Labels: [Type] Enhancement

#115 Add reference to the demo site
  README.md
Labels: [Type] Documentation

#66 Variation: "Pitch"
  assets/fonts/inter/Inter-VariableFont_slnt,wght.ttf
  assets/fonts/inter/LICENSE.txt
  styles/pitch.json
Labels: [Type] Style Variation

#173 fix spacing issues with variations
  styles/pitch.json
  styles/whisper.json
Labels: [Type] Bug

#185 Add spacer block to post meta pattern
  patterns/post-meta.php
Labels: [Type] Bug

#199 Update heading levels in header and home template
  parts/comments.html
  parts/header.html
  patterns/hidden-comments.php
  templates/home.html
Labels: [Type] Enhancement
