Repository WordPress/twentytwentythree, pull requests merged in 2022-08, with the labels that each got.

#11 Fix order of style variations
  styles/example2.json
  styles/example3.json
  styles/example4.json
  styles/example5.json
Labels: [Type] Bug

#21 Remove stray comma from example-five.json
  styles/example5.json
Labels: [Type] Bug, Good First Issue

#35 Update readme to include more information about style variations
  README.md
Labels: [Type] Documentation

#31 Remove opinion from templates
  patterns/footer-default.php
  patterns/hidden-404.php
  templates/archive.html
  templates/home.html
  templates/index.html
  templates/page-no-separators.html
  templates/page.html
  templates/search.html
  templates/single-no-separators.html
  templates/single.html
  theme.json
Labels: [Type] Enhancement

#39 Clean base theme theme.json file
  theme.json
Labels: [Type] Enhancement

#29 Add CS and linting with required GitHub workflows
  .github/workflows/lint.yml
  .nvmrc
  .phpcs.xml.dist
  .stylelintrc.json
  bin/phpcbf.sh
  composer.json
  composer.lock
  package-lock.json
  package.json
Labels: [Type] Code Quality, [Type] Discussion

#51 Fix PHPCS errors and file permissions
  bin/phpcbf.sh
  package-lock.json
  patterns/footer-default.php
  patterns/hidden-404.php
Labels: [Type] Code Quality

#79 Update font format to woff2 for DM Sans font family
  assets/fonts/dm-sans/DMSans-Bold-Italic.woff2
  assets/fonts/dm-sans/DMSans-Bold.ttf
  assets/fonts/dm-sans/DMSans-Bold.woff2
  assets/fonts/dm-sans/DMSans-BoldItalic.ttf
  assets/fonts/dm-sans/DMSans-Italic.ttf
  assets/fonts/dm-sans/DMSans-Regular-Italic.woff2
  assets/fonts/dm-sans/DMSans-Regular.ttf
  assets/fonts/dm-sans/DMSans-Regular.woff2
  theme.json
Labels: [Type] Enhancement

#53 Remove default italics
  theme.json
Labels: [Status] Needs Decision

#80 Replace default link color variable
  theme.json
Labels: [Type] Bug

#82 Add minimum value for small and medium sizes
  theme.json
Labels: [Type] Enhancement

#85 Update contributors doc
  CONTRIBUTORS.md
Labels: [Type] Documentation

#52 Update spacing presets
  parts/header.html
  patterns/footer-default.php
  templates/archive.html
  templates/home.html
  templates/index.html
  templates/page.html
  templates/search.html
  templates/single-no-separators.html
  templates/single.html
  theme.json
Labels: [Type] Enhancement

#91 Escaping and translation enhancements for patterns
  patterns/call-to-action.php
  patterns/hidden-404.php
Labels: [Type] Code Quality

#55 Update single and page, add comments part
  parts/comments.html
  templates/page-no-separators.html
  templates/page.html
  templates/single-no-separators.html
  templates/single.html
  theme.json
Labels: [Status] Needs Decision

#81 Update example variation font styles
  assets/fonts/dm-sans/DMSans-Bold-Italic.woff2
  assets/fonts/dm-sans/DMSans-Bold.woff2
  styles/example2.json
  styles/example4.json
  styles/example5.json
  theme.json
Labels: [Type] Enhancement

#83 Update navigation and site title styles
  theme.json
Labels: [Type] Enhancement

#103 Search and archive templates: update spacing
  templates/archive.html
  templates/search.html
  theme.json
Labels: [Type] Bug, [Type] Enhancement

#111 Update home template
  templates/archive.html
  templates/home.html
  templates/search.html
  theme.json
Labels: [Type] Enhancement

#123 Add a 'design specification' doc
  DESIGN-SPEC.md
  README.md
Labels: [Type] Documentation

#113 Update header and footer spacing
  parts/header.html
  patterns/footer-default.php
  theme.json
Labels: [Type] Enhancement

#132 Update contributors doc
  CONTRIBUTORS.md
Labels: [Type] Documentation

#131 Remove duplicate elements key from site-title
  theme.json
Labels: [Type] Bug

#121 WIP: Update templates to use the new layout setting
  parts/comments.html
  parts/header.html
  patterns/footer-default.php
  templates/404.html
  templates/archive.html
  templates/blank.html
  templates/blog-alternative.html
  templates/home.html
  templates/index.html
  templates/page.html
  templates/search.html
  templates/single.html
Labels: [Type] Enhancement, Good First Issue
